# configuration od the localization
dynamic_process_noise_covariance: true
# frequency della localization
frequency: 50
# frame a cui il sistema è connesso
map_frame: map
# sensori utilizzati. Un unico sensore imu
imu0: imu/data # topic a cui ci si sottoscrive per ottenere i dati del sensore
# configurazione de sensore
imu0_config: [false, false, false, # non da la posizione
              false, true, false,  
              false, false, false, # speed non viene data
              false, true, false, 
              true, false, true]   # accelerazione viene data
imu0_differential: false # non funzionano in modo differenziale
imu0_relative: false # gives absolute values
imu0_remove_gravitational_acceleration: true # non considerano l'accelerazione di gravità
odom0: odom
# configurazione della odometry
odom0_config: [true, true, false, # x, y robot
               false, false, true, # theta robot
               true, true, false, # vx, vy robot
               false, false, true, # velocità angolare robot
               false, false, false]
odom0_differential: false
odom0_relative: false

# covarianze dell'ekf
process_noise_covariance: [0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0.1,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
                           0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0.025, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0004, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

publish_tf: true
two_d_mode: true
